# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "maria-back-me-up"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/maria-back-me-up"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/DATA-DOG/go-sqlmock/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/aws/aws-sdk-go/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/coreos/go-oidc/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-mysql-org/go-mysql/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-sql-driver/mysql/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/gorilla/sessions/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/go-multierror/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/labstack/echo/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/namsral/flag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/ncw/swift/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/pingcap/errors/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/pingcap/tidb/pkg/parser/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/pkg/errors/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_golang/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/robfig/cron/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sirupsen/logrus/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/net/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/oauth2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sync/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sys/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/api/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/apimachinery/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/client-go/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/filippo.io/edwards25519/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/beorn7/perks/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cespare/xxhash/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/emicklei/go-restful/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/fxamacker/cbor/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/go-logr/logr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonpointer/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/jsonreference/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/cmdutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/conv/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/fileutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/jsonname/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/jsonutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/jsonutils/fixtures_test/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/loading/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/mangling/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/netutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/stringutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/typeutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/swag/yamlutils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/testify/enable/yaml/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-openapi/testify/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/go-task/slim-sprig/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/goccy/go-json/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/gogo/protobuf/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/gnostic-models/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/google/gofuzz/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/pprof/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/google/uuid/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/gorilla/securecookie/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/hashicorp/errwrap/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  "vendor/github.com/jmespath/go-jmespath/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/jmespath/go-jmespath/internal/testify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/json-iterator/go/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/kr/pretty/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kr/text/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/kylelemons/godebug/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/labstack/gommon/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mattn/go-colorable/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/mattn/go-isatty/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/modern-go/concurrent/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/modern-go/reflect2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/munnerz/goautoneg/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/onsi/ginkgo/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/onsi/gomega/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/pingcap/failpoint/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/pingcap/log/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/pquerna/cachecontrol/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_model/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/common/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/procfs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/rogpeppe/go-internal/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/shopspring/decimal/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/spf13/pflag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/stretchr/objx/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/valyala/bytebufferpool/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/valyala/fasttemplate/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/x448/float16/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/atomic/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/goleak/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/multierr/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.uber.org/zap/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/go.yaml.in/yaml/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.yaml.in/yaml/v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/crypto/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/term/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/text/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/time/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/tools/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/google.golang.org/protobuf/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/check.v1/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/evanphx/json-patch.v4/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/go-jose/go-jose.v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/gopkg.in/inf.v0/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/natefinch/lumberjack.v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/k8s.io/klog/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/kube-openapi/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/k8s.io/utils/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/json/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/randfill/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/structured-merge-diff/v6/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/sigs.k8s.io/yaml/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"
